version: '3'

services:
  cert-manager:
    build: .
    environment:
      - DIGITALOCEAN_TOKEN=${DIGITALOCEAN_TOKEN}
      - DIGITALOCEAN_CDN_ORIGIN=${DIGITALOCEAN_CDN_ORIGIN}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - CLOUDFLARE_API_KEY=${CLOUDFLARE_API_KEY}
      - CLOUDFLARE_EMAIL=${CLOUDFLARE_EMAIL}
    image: cert-manager
    container_name: cert-manager
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "50"
    restart: always
    volumes:
      - ./letsencrypt:/etc/letsencrypt
